linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: examples/
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - errcheck